name    'sirbrillig-wordpresscopy'
version '0.1.0'
author 'sirbrillig'
license 'Apache License, Version 2.0'
summary 'Allows copying an existing Wordpress site.'
description "Using two files, a tar of an existing WordPress install directory and a sql file of the site's database (generated by mysqldump), re-create the WordPress site."

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/mysql', '>= 0.6.1'
